apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ml-model-deployment
  namespace: ml-testing
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model-container
        image: apple1002/ml-model-api:1.2
        ports:
        - containerPort: 5000
