apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
  namespace: ml-testing
spec:
  selector:
    app: ml-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
